name: Deploy React App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -r -o StrictHostKeyChecking=no ./ ubuntu@18.118.18.178:~/MovieApp

      - name: Build and run Docker on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.118.18.178 << 'EOF'
          cd ~/MovieApp
          docker stop react-app || true
          docker rm react-app || true
          docker build -t react-app .
          docker run -d -p 80:80 --name react-app react-app
          EOF
